name: hello-ci

on:
  push:
    branches: [ci-pipeline-iteration]
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello! CI is running."